const hotelsData = [
    {
        name: 'Hotel Buenos Aires',
        address: '123 Main St, Buenos Aires, Argentina',
        address_url: 'https://www.example.com/hotel-buenos-aires',
        price: 150.00,
        email: 'hotel1@argentina.com',
        image: 'image1_argentina.jpg',
        countryId: 1,
    },
    {
        name: 'Hotel Rio de Janeiro',
        address: '456 Beach Ave, Rio de Janeiro, Brazil',
        address_url: 'https://www.example.com/hotel-rio-de-janeiro',
        price: 200.00,
        email: 'hotel2@brazil.com',
        image: 'image2_brazil.jpg',
        countryId: 2,
    },
    {
        name: 'Hotel Santiago',
        address: '789 Plaza St, Santiago, Chile',
        address_url: 'https://www.example.com/hotel-santiago',
        price: 250.00,
        email: 'hotel3@chile.com',
        image: 'image3_chile.jpg',
        countryId: 3,
    },
    {
        name: 'Hotel Bogota',
        address: '101 Downtown St, Bogota, Colombia',
        address_url: 'https://www.example.com/hotel-bogota',
        price: 180.00,
        email: 'hotel4@colombia.com',
        image: 'image4_colombia.jpg',
        countryId: 4,
    },
    {
        name: 'Hotel Quito',
        address: '202 Mountain View, Quito, Ecuador',
        address_url: 'https://www.example.com/hotel-quito',
        price: 160.00,
        email: 'hotel5@ecuador.com',
        image: 'image5_ecuador.jpg',
        countryId: 5,
    },
    {
        name: 'Hotel Mexico City',
        address: '303 Central Ave, Mexico City, Mexico',
        address_url: 'https://www.example.com/hotel-mexico-city',
        price: 220.00,
        email: 'hotel6@mexico.com',
        image: 'image6_mexico.jpg',
        countryId: 6,
    },
    {
        name: 'Hotel Lima',
        address: '404 Seaside St, Lima, Peru',
        address_url: 'https://www.example.com/hotel-lima',
        price: 190.00,
        email: 'hotel7@peru.com',
        image: 'image7_peru.jpg',
        countryId: 7,
    },
    {
        name: 'Hotel Montevideo',
        address: '505 Ocean View, Montevideo, Uruguay',
        address_url: 'https://www.example.com/hotel-montevideo',
        price: 170.00,
        email: 'hotel8@uruguay.com',
        image: 'image8_uruguay.jpg',
        countryId: 8,
    },
    {
        name: 'Hotel Caracas',
        address: '606 Hillside Ave, Caracas, Venezuela',
        address_url: 'https://www.example.com/hotel-caracas',
        price: 240.00,
        email: 'hotel9@venezuela.com',
        image: 'image9_venezuela.jpg',
        countryId: 9,
    },
    {
        name: 'Hotel Asuncion',
        address: '707 Plaza Blvd, Asuncion, Paraguay',
        address_url: 'https://www.example.com/hotel-asuncion',
        price: 200.00,
        email: 'hotel10@paraguay.com',
        image: 'image10_paraguay.jpg',
        countryId: 10,
    },
    // Agrega más hoteles según sea necesario
];

module.exports = {
    hotelsData
}